# EdX Text Data Exporatory Data Analysis Shell

To get this to work, you will need to create a .data directory in the root of the vip-nlp
After this has been done, put the PRIVATE data in that folder. DO NOT check this data in anywhere
Please sanitize your outputs by adding a random print statement when you're done
It might even be better to just never check this in with anything else

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

data_dir = os.path.join(Path(os.getcwd()).parent.parent, '.data')

# Get Comment Data
pdf_comments = pd.read_csv(os.path.join(data_dir, 'Forum comment ferpa.csv'))

data_dir

'C:\\Users\\tehho\\Documents\\OMSCS\\VIP\\vip-nlp\\.data'

Looks like we have something at the beginning of all the id's, we should probably drop those

In [2]:
# Grab ids
ids = pdf_comments['id']

# Everything starts with \\x35 so it is safe to drop
# You can fiddle with the 4 below to see how many instaces of different vals we have
ids.apply(lambda x: x[:4]).unique()

array(['\\x35'], dtype=object)

In [3]:
# What class has the most posts?
pdf_comments.groupby('course_id').count()['id'].reset_index().sort_values('id', ascending=False)

                          course_id    id
0      course-v1:GTx+CS1301x+1T2017  3478
50   course-v1:GTx+ISYE6501x+2T2017  1051
1     course-v1:GTx+CS1301xI+1T2018   430
64    course-v1:GTx+MGT6203x+2T2018   415
39     course-v1:GTx+ICT100x+1T2016   382
27       course-v1:GTx+HCIxI+2T2019   371
5    course-v1:GTx+CS1301xII+1T2018   266
2     course-v1:GTx+CS1301xI+1T2019   264
8   course-v1:GTx+CS1301xIII+1T2018   239
11   course-v1:GTx+CS1301xIV+1T2018   145
53  course-v1:GTx+ISYE6501x+2T2019b   121
3     course-v1:GTx+CS1301xI+3T2018   117
61     course-v1:GTx+MGT1000+3T2018   116
6    course-v1:GTx+CS1301xII+1T2019   115
55   course-v1:GTx+ISYE6501x+3T2018   115
49   course-v1:GTx+ISYE6501x+1T2020   112
9   course-v1:GTx+CS1301xIII+1T2019   105
7    course-v1:GTx+CS1301xII+3T2018    94
37   course-v1:GTx+HI2018xII+1T2019    92
54   course-v1:GTx+ISYE6501x+3T2017    81
10  course-v1:GTx+CS1301xIII+3T2018    80
48   course-v1:GTx+ISYE6501x+1T2019    78
47   course-v1:GTx+ISYE6501x+1T2018    77
13   course-v1:GTx+CS1301xIV+3T2018    72
24    course-v1:GTx+CSE6040x+2T2017    58
40     course-v1:GTx+ICT100x+3T2017    57
28      course-v1:GTx+HCIxII+2T2019    52
58    course-v1:GTx+ISYE6669+2T2018    50
60     course-v1:GTx+MGT1000+1T2018    44
67    course-v1:GTx+MGT6753x+2T2017    41
..                              ...   ...
26   course-v1:GTx+CSE6040x+2T2019a    19
66    course-v1:GTx+MGT6753x+1T2019    19
62    course-v1:GTx+MGT6203x+1T2018    18
35    course-v1:GTx+HDM1.2aX+3T2018    18
22    course-v1:GTx+CSE6040x+1T2019    18
38  course-v1:GTx+HI2018xIII+1T2019    13
45   course-v1:GTx+ISYE6414x+3T2018    13
25    course-v1:GTx+CSE6040x+2T2019    12
41    course-v1:GTx+ISYE6402+2T2018    11
34    course-v1:GTx+HDM1.2aX+2T2017    11
52  course-v1:GTx+ISYE6501x+2T2019a    10
19      course-v1:GTx+CS7641+1T2018     8
4     course-v1:GTx+CS1301xI+3T2019     6
56   course-v1:GTx+ISYE6644x+2T2017     6
21    course-v1:GTx+CSE6040x+1T2018     5
69     course-v1:GTx+MGT6754+2T2018     5
16      course-v1:GTx+CS6400+1T2018     4
32    course-v1:GTx+HDM1.1aX+3T2018     3
33    course-v1:GTx+HDM1.2aX+1T2019     3
18     course-v1:GTx+CS6400x+2T2017     3
17      course-v1:GTx+CS6400+2T2018     3
15     course-v1:GTx+CS6035+2T2019a     3
65   course-v1:GTx+MGT6203x+2T2018a     3
20     course-v1:GTx+CS7641x+2T2017     2
42   course-v1:GTx+ISYE6402x+1T2018     2
51   course-v1:GTx+ISYE6501x+2T2018     1
63    course-v1:GTx+MGT6203x+1T2020     1
14      course-v1:GTx+CS6035+1T2019     1
46   course-v1:GTx+ISYE6420+2T2018a     1
68    course-v1:GTx+MGT6753x+3T2018     1

[70 rows x 2 columns]

In [4]:
# Get thread data
pdf_threads = pd.read_csv(os.path.join(data_dir, 'Forum thread ferpa.csv'))

pdf_threads

,id,user_id,commentable_id,course_id,closed,thread_type,title,body,anonymous,anonymous_to_peers,comment_count,upvotes,downvotes,last_activity_at,updated_at,created_at
0,\x35626565353731336566356233333039626630303161...,1653997,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,SartBook 3.1 question error?,![question error in smart book - section 3.1][...,False,False,1,0,0,11/16/18 5:36,11/16/18 5:36,11/16/18 5:35
1,\x35626438316331636566356233333039623330303063...,19870175,fd01b70fb9aa5b15257e2dd8216da15492778055,course-v1:GTx+CS1301xII+1T2018,False,discussion,Question about Coding Problem 3.4.10,i have checked my code in python IDLE and it s...,False,False,2,0,0,10/30/18 14:11,10/30/18 14:11,10/30/18 8:53
2,\x35626338343734366566356233333039666230303030...,19989065,gt-cs1301x-3-3,course-v1:GTx+CS1301xII+1T2018,False,discussion,Bug on 3.3.5 Worked Example 1 (External resour...,"In 3.3.5 Worked Example 1 (External resource),...",False,False,0,0,0,10/18/18 8:41,10/18/18 8:41,10/18/18 8:41
3,\x35626163626637346135323230333039346130303363...,15571936,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Problem with voraceum,I am currently auditing this course on Edx. Th...,False,False,0,0,0,9/27/18 11:31,9/27/18 11:31,9/27/18 11:31
4,\x35623963636334666135323230333039393530303331...,6865127,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Vocareum seems to be broken,"Hi, in the coding exercises (e.g. 3.1.5 Coding...",False,False,1,0,0,9/15/18 17:07,9/15/18 17:07,9/15/18 9:09
5,\x35623862636533336135323230333039353630303230...,9194894,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Not able to crack 3.3.12 problem,Hi - Can anyone help me with some tips on how ...,False,False,1,0,0,9/2/18 13:09,9/2/18 13:09,9/2/18 11:49
6,\x35623862623661336135323230333039363230303231...,3356634,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,time rounout in problem 3.3.4,Hello. I test this problem in another IDLE and...,False,False,1,0,0,9/2/18 12:36,9/2/18 12:36,9/2/18 10:08
7,\x35623665373532306135323230333039353330303130...,6090112,8483dd4a8aa0583c7d9989b3069271d5ad1921e2,course-v1:GTx+CS1301xII+1T2018,False,discussion,My PERSON PERSON animations,Follow these links to check them out: https:...,False,False,0,0,0,8/11/18 5:33,8/12/18 2:48,8/11/18 5:33
8,\x35623566306135613362306162633039613630303038...,13818697,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Problems with Problem 3.4.12 Sample Answers,There seem to be a few issues with the sample ...,False,False,1,0,0,8/18/18 18:53,8/18/18 18:53,7/30/18 12:53
9,\x35623561656164613362306162633039633130303035...,19909385,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,"difference of ord(i) and ord(""i"")","Hey, I just have encountered something I woul...",False,False,2,0,0,7/29/18 6:53,7/29/18 6:53,7/27/18 9:50
10,\x35623464663338386230333433373039316230303030...,18597896,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,proctoring: how does it work ?,Hello How does the proctoring during the exam ...,False,False,3,0,0,8/4/18 19:28,8/4/18 19:28,7/17/18 13:47
11,\x35613564356166393761636632643038333730303137...,17507206,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Nick from UGA,"Hello everyone, My name is PERSON and I live ...",False,False,0,0,0,1/16/18 1:52,1/16/18 1:52,1/16/18 1:52
12,\x35613562623565306435636237373061373530303132...,17450946,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Priya from Atlanta, Ga","Hi everyone! I'm Priya from Atlanta, Georgia. ...",False,False,2,0,0,1/18/18 14:21,1/18/18 14:21,1/14/18 19:56
13,\x35613539323661353434613135303038623230303130...,17472539,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Priya from Atlanta,Hi everyone! I'm Priya from Atlanta. BS ISyE '...,False,False,0,0,0,1/12/18 21:20,1/12/18 21:30,1/12/18 21:20
14,\x35613536393835363761636632643038323230303131...,4371720,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Daniel from Maryland,"Hi, I'm PERSON. I graduated undergrad from GT ...",False,False,0,0,0,1/10/18 22:48,1/10/18 22:48,1/10/18 22:48
15,\x35613536376239633434613135303038613330303066...,15659054,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Sur from Dallas, TX","Hey guys, I'm PERSON, and I work as a BI Dev...",False,False,0,0,0,1/10/18 20:46,1/10/18 20:47,1/10/18 20:46
16,\x35613536376232666435636237373061616530303130...,17453923,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Mika from Chicago, IL",Hi everyone! I'm an IT consultant transitionin...,False,False,0,0,0,1/10/18 20:44,1/10/18 20:44,1/10/18 20:44
17,\x35613535383664303434613135303038386530303066...,17460028,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"PERSON: Michelle, Los Angeles","Hi All, my name is PERSON PERSON. I am a syste...",False,False,0,0,0,1/10/18 3:21,1/10/18 3:21,1/10/18 3:21
18,\x35613535313964643761636632643038323930303064...,17473077,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,PERSON from Atlanta,"Hi All - I'm PERSON PERSON, born and raised ar...",False,False,0,0,0,1/9/18 19:37,1/9/18 19:37,1/9/18 19:37
19,\x35613535303534323761636632643038353930303066...,17455718,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello from Houston!,Hi everyone :) I'm PERSON PERSON and I moved t...,False,False,1,0,0,1/10/18 6:14,1/10/18 6:14,1/9/18 18:09
20,\x35613534626534653761636632643038346430303063...,17449216,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hi All!,I'm PERSON from the back woods of New Hampshir...,False,False,0,0,0,1/9/18 13:06,1/9/18 13:06,1/9/18 13:06
21,\x35613533656665313761636632643038353330303063...,17457462,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,PERSON to Esmond,"Howdy y'all! I'm PERSON PERSON, and I hail fr...",False,False,0,0,0,1/8/18 22:25,1/8/18 22:25,1/8/18 22:25
22,\x35613534343637343434613135303038393430303066...,17449860,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello,"Hello All, I'm PERSON originally from Colombi...",False,False,0,0,0,1/9/18 4:35,1/9/18 4:35,1/9/18 4:35
23,\x35613534336632323434613135303038386530303065...,15661480,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Winnie from California,"Hi, I am PERSON from San Ramon, California. I ...",False,False,0,0,0,1/9/18 4:03,1/9/18 4:03,1/9/18 4:03
24,\x35613534333163663761636632643038326630303063...,17459729,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Tess from Nebraska,"Hello, I'm PERSON PERSON and I currently live ...",False,False,0,0,0,1/9/18 3:06,1/9/18 3:06,1/9/18 3:06
25,\x35613534306334363434613135303038633430303130...,17458196,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello from PERSON PERSON PERSONPERSONOTP,"GreetingsPERSONfellowPERSONlearners, PERSONPE...",False,False,1,0,0,1/9/18 0:51,1/9/18 0:51,1/9/18 0:26
26,\x35613534303866636435636237373061393030303065...,17453675,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Intro - Mohit Aggarwal,"Hello everyone, My name is PERSON PERSON. I l...",False,False,0,0,0,1/9/18 0:12,1/9/18 0:12,1/9/18 0:12
27,\x35613534303837386435636237373061366630303066...,15658946,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Thom's Fabulous Introduction,There are some who call me... Thom. I am curr...,False,False,0,0,0,1/9/18 0:10,1/9/18 0:10,1/9/18 0:10
28,\x35613533663236323434613135303038393730303066...,17453115,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hey!,Hello everyone! My name is PERSON PERSON. I j...,False,False,0,0,0,1/8/18 22:36,1/8/18 22:36,1/8/18 22:36
29,\x35623830366634366333303561643039666430303162...,20399735,course,course-v1:GTx+ISYE6501x+3T2018,False,discussion,Hello from Seattle!,"Hi, I'm PERSON.",False,False,1,0,0,8/25/18 21:36,8/25/18 21:36,8/24/18 20:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9254,\x35383962393330366631373035363037376530303034...,11943609,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,Hello,Just wanted to introduce myself...I'm Alex fro...,False,False,1,0,0,2/8/17 23:07,2/8/17 23:07,2/8/17 21:52
9255,\x35383962376332646461643636633038343130303034...,13275078,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,External site access,I entered my user Id and password that I use t...,False,False,3,0,0,2/10/17 5:53,2/10/17 5:53,2/8/17 20:14
9256,\x35383938633261336631373035363037376530303032...,8314032,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,Slack.com,Hi everyone! How we supposed to connect with P...,False,False,1,0,0,2/6/17 19:15,2/6/17 19:15,2/6/17 18:38
9257,\x35653133663239373935623036323039306530303339...,26584146,gt-cs1301x-2-3,course-v1:GTx+CS1301xI+3T2019,False,question,is the Coding Problem 2.3.7 buggy ?,the code i sent works fine in my environment (...,False,False,0,0,0,1/7/20 2:53,1/7/20 2:53,1/7/20 2:53
9258,\x35653132386266383766656265353039363430303236...,3981633,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xI+3T2019,False,question,coding exercise 2.2.6 - bug??,my code is correct how come it still saying th...,False,False,1,0,0,1/6/20 4:52,1/6/20 4:52,1/6/20 1:23
9259,\x35653063666330636337363237373039323430303232...,12738350,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xI+3T2019,False,discussion,Atom as an Editor,When mentioning editors for python I didn't se...,False,False,1,1,0,1/2/20 0:29,1/2/20 0:29,1/1/20 20:07
9260,\x35636533373839366438656162313039363630303138...,23228646,d75bc9f21aa953b6a0d3ad841a56bd4735fccb36,course-v1:GTx+CS1301xIV+1T2019,False,discussion,yey,yey,False,False,4,0,0,9/9/19 19:24,9/9/19 19:24,5/21/19 4:03
9261,\x35643931613536616330366432363039366630303264...,10099722,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xIV+1T2019,False,question,"Problem 5.2.2, Part 3 of 3",This problem is wrongly graded. How to report it?,False,False,0,0,0,9/30/19 6:49,9/30/19 6:49,9/30/19 6:49
9262,\x35643232386463316438656162313039356530303361...,12043501,gt-cs1301x-Technical-Support,course-v1:GTx+CS1301xIV+1T2019,False,question,"Problem 5.2.2, Part 3 of 3 - seems to be an is...",The auto-grader does not recognise the answer ...,False,False,1,0,0,8/25/19 1:16,8/25/19 1:16,7/8/19 0:26
9263,\x35636335666237643064616663363039396430303061...,9380221,gt-cs1301x-fps,course-v1:GTx+CS1301xIV+1T2019,False,discussion,Final Problem 4,"Hello, I just finished the connect 4 final pr...",False,False,1,0,0,12/9/19 0:51,12/9/19 0:51,4/28/19 19:14
9264,\x35633433333730373538616463623039366530303131...,15099592,gt-cs1301x-Social,course-v1:GTx+CS1301xIV+1T2019,False,discussion,PERSON yourselves!,"Hey everyone, and welcome to PERSON! I am a bo...",False,False,1,0,0,11/1/19 10:12,11/1/19 10:12,1/19/19 14:41
9265,\x35653163303665353766656265353039366130303266...,26054730,1c47923a60039e404c8c611bb6e3853a11545e2f,course-v1:GTx+HCIxIII+2T2019,False,discussion,why designers matter,"I’ve seen it happen too many times, when devel...",False,False,0,0,0,1/13/20 5:57,1/13/20 5:57,1/13/20 5:57
9266,\x35653162653962396337363237373039316430303264...,17961603,2afa1f7f9223c8e9b981ee2d68f74f825727aeb1,course-v1:GTx+HCIxIII+2T2019,False,question,improving mooc,Allow us to take notes on the same interface. ...,False,False,0,0,0,1/13/20 3:53,1/13/20 3:53,1/13/20 3:53
9267,\x35653161613730326337363237373039363030303432...,25172170,d935eb4e7b1a8272cb70c46d13e6848237f9ac5d,course-v1:GTx+HCIxIII+2T2019,False,discussion,Prototyping,I can create a card prototype to show teachers...,False,False,0,0,0,1/12/20 4:56,1/12/20 4:56,1/12/20 4:56
9268,\x35653065353366346337363237373039333330303239...,25172170,4f3a72174d0bae3a1dcfb15ccf293de470f55af2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Needfinding: Education,I can observe teachers and students in a schoo...,False,False,0,0,0,1/2/20 20:35,1/2/20 20:35,1/2/20 20:35
9269,\x35653065353233626337363237373039343230303332...,25172170,e478841103a48711484f884297bca5988eec3ad2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Design Challenge: Needfinding,Start with observations or interviews. Then co...,False,False,0,0,0,1/2/20 20:27,1/2/20 20:27,1/2/20 20:27
9270,\x35653065353063303935623036323039306230303238...,25172170,95c784fe2c116a1d78367875887ff3e49aab3d2c,course-v1:GTx+HCIxIII+2T2019,False,discussion,Reflections: Surveys,Question number 1 gives no indication of what ...,False,False,0,0,0,1/2/20 20:21,1/2/20 20:21,1/2/20 20:21
9271,\x35646537656165393935623036323039323330303138...,25172170,6e0f814acdaa4cf2d1315f2654331b9ff981b253,course-v1:GTx+HCIxIII+2T2019,False,discussion,Design Cycle in education,"Speaking with teachers, students, and parents ...",False,False,0,0,0,12/4/19 17:20,12/4/19 17:20,12/4/19 17:20
9272,\x35646537343339666337363237373039363330303232...,16397,d935eb4e7b1a8272cb70c46d13e6848237f9ac5d,course-v1:GTx+HCIxIII+2T2019,False,discussion,Prototyping for internal operational tools,I would start with verbal first to talk with u...,False,False,0,0,0,12/4/19 5:26,12/4/19 5:26,12/4/19 5:26
9273,\x35646266366537656337363237373039336630303038...,16397,e478841103a48711484f884297bca5988eec3ad2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Needfinding for book reading,Figure out our targeted users and brainstorm t...,False,False,0,0,0,11/4/19 0:19,11/4/19 0:19,11/4/19 0:19
9274,\x35646266366161323935623036323039353630303037...,16397,95c784fe2c116a1d78367875887ff3e49aab3d2c,course-v1:GTx+HCIxIII+2T2019,False,discussion,What's wrong with the survey?,* the first question and the third should labe...,False,False,0,0,0,11/4/19 0:02,11/4/19 0:02,11/4/19 0:02
9275,\x35646233386331356337363237373039323030303030...,16397,d84fefc5541960f7b550df2c268c6d380ab12b6a,course-v1:GTx+HCIxIII+2T2019,False,discussion,Data Use Policy and Consent,"Personally, I would want Facebook to get an ex...",True,False,0,0,0,10/25/19 23:58,10/25/19 23:58,10/25/19 23:58
9276,\x35646166633861356330366432363039346630303437...,16397,6e0f814acdaa4cf2d1315f2654331b9ff981b253,course-v1:GTx+HCIxIII+2T2019,False,discussion,Large System Operational Tools,The users I need are the people who handle ope...,False,False,1,0,0,10/23/19 3:35,10/23/19 3:35,10/23/19 3:27
9277,\x35646166396566633834343532613037616330303436...,16397,1c47923a60039e404c8c611bb6e3853a11545e2f,course-v1:GTx+HCIxIII+2T2019,False,discussion,Importance of the Design,Well the reason why I decided to take this cla...,False,False,0,0,0,10/23/19 0:29,10/23/19 0:29,10/23/19 0:29
9278,\x35616665346166663834343532613038343530303565...,17452853,49e7d0f24c50cfe627e46d6b2f8b9cfc828814a3,course-v1:GTx+ISYE6501x+2T2018,False,discussion,"Hello from Grace, Toronto, CA","Hi all, this is Grace! Would love to meet anyo...",False,False,0,0,0,5/18/18 3:39,5/18/18 3:39,5/18/18 3:39
9279,\x35616661666164623234343531613039623230303561...,17450629,49e7d0f24c50cfe627e46d6b2f8b9cfc828814a3,course-v1:GTx+ISYE6501x+2T2018,False,discussion,Hello!,Hello all! My name is PERSON and I'm currently...,False,False,0,0,0,5/15/18 15:20,5/15/18 15:20,5/15/18 15:20
9280,\x35616631303330613834343532613038343230303536...,14334853,course,course-v1:GTx+MGT6203x+2T2018,False,discussion,Intended grading scale?,My final exam grade was rounded down 9.8% to f...,False,False,5,4,0,5/15/18 15:49,5/15/18 15:49,5/8/18 1:53
9281,\x35616630363738633234343531613039646330303532...,15680341,course,course-v1:GTx+MGT6203x+2T2018,False,question,Final Exam Grading Input,"Hi, as per the instructions we received last w...",True,False,1,0,0,5/7/18 16:30,5/7/18 16:30,5/7/18 14:49
9282,\x35613864303938333234343531613039626530303134...,6778107,8088b638e41c2c04751500584ee3d57eb21edc5d,course-v1:GTx+MGT6203x+2T2018,False,question,I am assigned to wrong session,"Dear Sir, Data Analytics for Business GTx - ...",False,False,1,0,0,3/8/18 14:51,3/8/18 14:51,2/21/18 5:54
9283,\x35613838623331663234343531613039656230303131...,17036256,course,course-v1:GTx+MGT6203x+2T2018,False,discussion,Syllabus Dates,Question about the syllabus due dates. It see...,False,False,2,0,0,2/19/18 3:37,2/19/18 3:37,2/17/18 22:56

In [18]:
pdf_comments['body'] = pdf_comments['body'].apply(lambda x: x.replace('PERSON', ' '))

In [15]:
person_free

0       Enter your answer without spaces! I was going ...
1                                   SmartBook that is :)
2       What is the answer for this question? I tried ...
3       Passed with output printed: 12 On the bubble  ...
4       I had the same problem with this question, I w...
5       ah, I see. And for '  I do it the other way ar...
6       I knew in my bones it was just a typo - I just...
7       I upgraded to ' ' and the exam questions I had...
8                                 I'm interested as well!
9       Hi, no I have not. Could you please provide th...
10                   I'd be interested in joining as well
11                              The question is the joke.
12      lol... I didn't even see the hint. Now I got i...
13      No, it's not because it's empty. It's because ...
14      Have you had a look at how the split() method ...
15      Hey  . I'm  . Seattle is my second favorite ci...
16                                              Yes, I am
17                               I am interested as well.
18      Ernest, I am also in Atlanta!  That is very ki...
19      Yeah, I am interested. I think it's a great idea!
20      Hi, will you be studying and doing homework ov...
21      Hi  .  I am in Plano as well!  Best of luck wi...
22      I'm on a PLOA but am part of Accenture Consult...
23      Nice to see someone else from the Twin Cities!...
24      I have a issue with this problem I don't know ...
25      Ok, so I figured it out - @ sheebanishat you a...
26      can you give us a hint? I'm on the same trail ...
27      Even though this is a different error than the...
28      There should be an install package option with...
29                                 Very helpful.  Thanks!
                              ...
9158    Hey everyone! 1) My name is     2) I am from K...
9159    Hi, I'm Beatrice, 18, from Malaysia. I just gr...
9160    Hi I'm   from New York. I'm a senior in high s...
9161    1. Hey Everyone! My name is  .  2. I am from I...
9162    Hi, there is an alternative way: if you have a...
9163    Hello! I'm   from California, USA. Excited to ...
9164                                              Yip yip
9165    it's a long way here for me,too...haha  i star...
9166    I'm a little bit confused with paper prototypi...
9167    An interesting article. It's true that the use...
9168    I agree with you. I think persons would be an ...
9169    It's a good point. Social interaction could be...
9170    3 is a good point! The original question defin...
9171    Thanks for the great summary. IIRC the author ...
9172    The primary users would be the coworkers that ...
9173    Hi Sumit - Good to know you and I will be in a...
9174    Could you provide some reasoning for using a 1...
9175    I submitted the same way as jporta44 (submitte...
9176    Can someone confirm the proper way to upload d...
9177    Yes, mine shows: ![Final Time listed][1]  I wa...
9178    Is there a time limitation (x hours) on comple...
9179    Hello, I am checking in to see if you can shar...
9180    If possible, can we get an answer guide on qui...
9181    These discussion threads are not quite clearin...
9182    Will the 2 lowest quiz grades be dropped as in...
9183    I had RStudio crashing (every time) when estim...
9184    I could only get the accurate numbers when usi...
9185    I have the same issue here. Thanks for pointin...
9186                     The exams are not available yet.
9187    There won't be any homework assignments for th...
Name: body, Length: 9188, dtype: object

In [17]:
pdf_threads

,id,user_id,commentable_id,course_id,closed,thread_type,title,body,anonymous,anonymous_to_peers,comment_count,upvotes,downvotes,last_activity_at,updated_at,created_at
0,\x35626565353731336566356233333039626630303161...,1653997,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,SartBook 3.1 question error?,![question error in smart book - section 3.1][...,False,False,1,0,0,11/16/18 5:36,11/16/18 5:36,11/16/18 5:35
1,\x35626438316331636566356233333039623330303063...,19870175,fd01b70fb9aa5b15257e2dd8216da15492778055,course-v1:GTx+CS1301xII+1T2018,False,discussion,Question about Coding Problem 3.4.10,i have checked my code in python IDLE and it s...,False,False,2,0,0,10/30/18 14:11,10/30/18 14:11,10/30/18 8:53
2,\x35626338343734366566356233333039666230303030...,19989065,gt-cs1301x-3-3,course-v1:GTx+CS1301xII+1T2018,False,discussion,Bug on 3.3.5 Worked Example 1 (External resour...,"In 3.3.5 Worked Example 1 (External resource),...",False,False,0,0,0,10/18/18 8:41,10/18/18 8:41,10/18/18 8:41
3,\x35626163626637346135323230333039346130303363...,15571936,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Problem with voraceum,I am currently auditing this course on Edx. Th...,False,False,0,0,0,9/27/18 11:31,9/27/18 11:31,9/27/18 11:31
4,\x35623963636334666135323230333039393530303331...,6865127,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Vocareum seems to be broken,"Hi, in the coding exercises (e.g. 3.1.5 Coding...",False,False,1,0,0,9/15/18 17:07,9/15/18 17:07,9/15/18 9:09
5,\x35623862636533336135323230333039353630303230...,9194894,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Not able to crack 3.3.12 problem,Hi - Can anyone help me with some tips on how ...,False,False,1,0,0,9/2/18 13:09,9/2/18 13:09,9/2/18 11:49
6,\x35623862623661336135323230333039363230303231...,3356634,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,time rounout in problem 3.3.4,Hello. I test this problem in another IDLE and...,False,False,1,0,0,9/2/18 12:36,9/2/18 12:36,9/2/18 10:08
7,\x35623665373532306135323230333039353330303130...,6090112,8483dd4a8aa0583c7d9989b3069271d5ad1921e2,course-v1:GTx+CS1301xII+1T2018,False,discussion,My PERSON PERSON animations,Follow these links to check them out: https:...,False,False,0,0,0,8/11/18 5:33,8/12/18 2:48,8/11/18 5:33
8,\x35623566306135613362306162633039613630303038...,13818697,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,Problems with Problem 3.4.12 Sample Answers,There seem to be a few issues with the sample ...,False,False,1,0,0,8/18/18 18:53,8/18/18 18:53,7/30/18 12:53
9,\x35623561656164613362306162633039633130303035...,19909385,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,"difference of ord(i) and ord(""i"")","Hey, I just have encountered something I woul...",False,False,2,0,0,7/29/18 6:53,7/29/18 6:53,7/27/18 9:50
10,\x35623464663338386230333433373039316230303030...,18597896,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xII+1T2018,False,discussion,proctoring: how does it work ?,Hello How does the proctoring during the exam ...,False,False,3,0,0,8/4/18 19:28,8/4/18 19:28,7/17/18 13:47
11,\x35613564356166393761636632643038333730303137...,17507206,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Nick from UGA,"Hello everyone, My name is PERSON and I live ...",False,False,0,0,0,1/16/18 1:52,1/16/18 1:52,1/16/18 1:52
12,\x35613562623565306435636237373061373530303132...,17450946,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Priya from Atlanta, Ga","Hi everyone! I'm Priya from Atlanta, Georgia. ...",False,False,2,0,0,1/18/18 14:21,1/18/18 14:21,1/14/18 19:56
13,\x35613539323661353434613135303038623230303130...,17472539,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Priya from Atlanta,Hi everyone! I'm Priya from Atlanta. BS ISyE '...,False,False,0,0,0,1/12/18 21:20,1/12/18 21:30,1/12/18 21:20
14,\x35613536393835363761636632643038323230303131...,4371720,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Daniel from Maryland,"Hi, I'm PERSON. I graduated undergrad from GT ...",False,False,0,0,0,1/10/18 22:48,1/10/18 22:48,1/10/18 22:48
15,\x35613536376239633434613135303038613330303066...,15659054,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Sur from Dallas, TX","Hey guys, I'm PERSON, and I work as a BI Dev...",False,False,0,0,0,1/10/18 20:46,1/10/18 20:47,1/10/18 20:46
16,\x35613536376232666435636237373061616530303130...,17453923,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"Mika from Chicago, IL",Hi everyone! I'm an IT consultant transitionin...,False,False,0,0,0,1/10/18 20:44,1/10/18 20:44,1/10/18 20:44
17,\x35613535383664303434613135303038386530303066...,17460028,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,"PERSON: Michelle, Los Angeles","Hi All, my name is PERSON PERSON. I am a syste...",False,False,0,0,0,1/10/18 3:21,1/10/18 3:21,1/10/18 3:21
18,\x35613535313964643761636632643038323930303064...,17473077,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,PERSON from Atlanta,"Hi All - I'm PERSON PERSON, born and raised ar...",False,False,0,0,0,1/9/18 19:37,1/9/18 19:37,1/9/18 19:37
19,\x35613535303534323761636632643038353930303066...,17455718,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello from Houston!,Hi everyone :) I'm PERSON PERSON and I moved t...,False,False,1,0,0,1/10/18 6:14,1/10/18 6:14,1/9/18 18:09
20,\x35613534626534653761636632643038346430303063...,17449216,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hi All!,I'm PERSON from the back woods of New Hampshir...,False,False,0,0,0,1/9/18 13:06,1/9/18 13:06,1/9/18 13:06
21,\x35613533656665313761636632643038353330303063...,17457462,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,PERSON to Esmond,"Howdy y'all! I'm PERSON PERSON, and I hail fr...",False,False,0,0,0,1/8/18 22:25,1/8/18 22:25,1/8/18 22:25
22,\x35613534343637343434613135303038393430303066...,17449860,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello,"Hello All, I'm PERSON originally from Colombi...",False,False,0,0,0,1/9/18 4:35,1/9/18 4:35,1/9/18 4:35
23,\x35613534336632323434613135303038386530303065...,15661480,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Winnie from California,"Hi, I am PERSON from San Ramon, California. I ...",False,False,0,0,0,1/9/18 4:03,1/9/18 4:03,1/9/18 4:03
24,\x35613534333163663761636632643038326630303063...,17459729,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Tess from Nebraska,"Hello, I'm PERSON PERSON and I currently live ...",False,False,0,0,0,1/9/18 3:06,1/9/18 3:06,1/9/18 3:06
25,\x35613534306334363434613135303038633430303130...,17458196,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hello from PERSON PERSON PERSONPERSONOTP,"GreetingsPERSONfellowPERSONlearners, PERSONPE...",False,False,1,0,0,1/9/18 0:51,1/9/18 0:51,1/9/18 0:26
26,\x35613534303866636435636237373061393030303065...,17453675,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Intro - Mohit Aggarwal,"Hello everyone, My name is PERSON PERSON. I l...",False,False,0,0,0,1/9/18 0:12,1/9/18 0:12,1/9/18 0:12
27,\x35613534303837386435636237373061366630303066...,15658946,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Thom's Fabulous Introduction,There are some who call me... Thom. I am curr...,False,False,0,0,0,1/9/18 0:10,1/9/18 0:10,1/9/18 0:10
28,\x35613533663236323434613135303038393730303066...,17453115,f8472353ff8fa0aed9c8800c68279d3a1796791f,course-v1:GTx+ISYE6501x+1T2018,False,discussion,Hey!,Hello everyone! My name is PERSON PERSON. I j...,False,False,0,0,0,1/8/18 22:36,1/8/18 22:36,1/8/18 22:36
29,\x35623830366634366333303561643039666430303162...,20399735,course,course-v1:GTx+ISYE6501x+3T2018,False,discussion,Hello from Seattle!,"Hi, I'm PERSON.",False,False,1,0,0,8/25/18 21:36,8/25/18 21:36,8/24/18 20:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9254,\x35383962393330366631373035363037376530303034...,11943609,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,Hello,Just wanted to introduce myself...I'm Alex fro...,False,False,1,0,0,2/8/17 23:07,2/8/17 23:07,2/8/17 21:52
9255,\x35383962376332646461643636633038343130303034...,13275078,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,External site access,I entered my user Id and password that I use t...,False,False,3,0,0,2/10/17 5:53,2/10/17 5:53,2/8/17 20:14
9256,\x35383938633261336631373035363037376530303032...,8314032,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301x+1T2017,False,discussion,Slack.com,Hi everyone! How we supposed to connect with P...,False,False,1,0,0,2/6/17 19:15,2/6/17 19:15,2/6/17 18:38
9257,\x35653133663239373935623036323039306530303339...,26584146,gt-cs1301x-2-3,course-v1:GTx+CS1301xI+3T2019,False,question,is the Coding Problem 2.3.7 buggy ?,the code i sent works fine in my environment (...,False,False,0,0,0,1/7/20 2:53,1/7/20 2:53,1/7/20 2:53
9258,\x35653132386266383766656265353039363430303236...,3981633,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xI+3T2019,False,question,coding exercise 2.2.6 - bug??,my code is correct how come it still saying th...,False,False,1,0,0,1/6/20 4:52,1/6/20 4:52,1/6/20 1:23
9259,\x35653063666330636337363237373039323430303232...,12738350,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xI+3T2019,False,discussion,Atom as an Editor,When mentioning editors for python I didn't se...,False,False,1,1,0,1/2/20 0:29,1/2/20 0:29,1/1/20 20:07
9260,\x35636533373839366438656162313039363630303138...,23228646,d75bc9f21aa953b6a0d3ad841a56bd4735fccb36,course-v1:GTx+CS1301xIV+1T2019,False,discussion,yey,yey,False,False,4,0,0,9/9/19 19:24,9/9/19 19:24,5/21/19 4:03
9261,\x35643931613536616330366432363039366630303264...,10099722,gt-cs1301x-General-Discussion,course-v1:GTx+CS1301xIV+1T2019,False,question,"Problem 5.2.2, Part 3 of 3",This problem is wrongly graded. How to report it?,False,False,0,0,0,9/30/19 6:49,9/30/19 6:49,9/30/19 6:49
9262,\x35643232386463316438656162313039356530303361...,12043501,gt-cs1301x-Technical-Support,course-v1:GTx+CS1301xIV+1T2019,False,question,"Problem 5.2.2, Part 3 of 3 - seems to be an is...",The auto-grader does not recognise the answer ...,False,False,1,0,0,8/25/19 1:16,8/25/19 1:16,7/8/19 0:26
9263,\x35636335666237643064616663363039396430303061...,9380221,gt-cs1301x-fps,course-v1:GTx+CS1301xIV+1T2019,False,discussion,Final Problem 4,"Hello, I just finished the connect 4 final pr...",False,False,1,0,0,12/9/19 0:51,12/9/19 0:51,4/28/19 19:14
9264,\x35633433333730373538616463623039366530303131...,15099592,gt-cs1301x-Social,course-v1:GTx+CS1301xIV+1T2019,False,discussion,PERSON yourselves!,"Hey everyone, and welcome to PERSON! I am a bo...",False,False,1,0,0,11/1/19 10:12,11/1/19 10:12,1/19/19 14:41
9265,\x35653163303665353766656265353039366130303266...,26054730,1c47923a60039e404c8c611bb6e3853a11545e2f,course-v1:GTx+HCIxIII+2T2019,False,discussion,why designers matter,"I’ve seen it happen too many times, when devel...",False,False,0,0,0,1/13/20 5:57,1/13/20 5:57,1/13/20 5:57
9266,\x35653162653962396337363237373039316430303264...,17961603,2afa1f7f9223c8e9b981ee2d68f74f825727aeb1,course-v1:GTx+HCIxIII+2T2019,False,question,improving mooc,Allow us to take notes on the same interface. ...,False,False,0,0,0,1/13/20 3:53,1/13/20 3:53,1/13/20 3:53
9267,\x35653161613730326337363237373039363030303432...,25172170,d935eb4e7b1a8272cb70c46d13e6848237f9ac5d,course-v1:GTx+HCIxIII+2T2019,False,discussion,Prototyping,I can create a card prototype to show teachers...,False,False,0,0,0,1/12/20 4:56,1/12/20 4:56,1/12/20 4:56
9268,\x35653065353366346337363237373039333330303239...,25172170,4f3a72174d0bae3a1dcfb15ccf293de470f55af2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Needfinding: Education,I can observe teachers and students in a schoo...,False,False,0,0,0,1/2/20 20:35,1/2/20 20:35,1/2/20 20:35
9269,\x35653065353233626337363237373039343230303332...,25172170,e478841103a48711484f884297bca5988eec3ad2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Design Challenge: Needfinding,Start with observations or interviews. Then co...,False,False,0,0,0,1/2/20 20:27,1/2/20 20:27,1/2/20 20:27
9270,\x35653065353063303935623036323039306230303238...,25172170,95c784fe2c116a1d78367875887ff3e49aab3d2c,course-v1:GTx+HCIxIII+2T2019,False,discussion,Reflections: Surveys,Question number 1 gives no indication of what ...,False,False,0,0,0,1/2/20 20:21,1/2/20 20:21,1/2/20 20:21
9271,\x35646537656165393935623036323039323330303138...,25172170,6e0f814acdaa4cf2d1315f2654331b9ff981b253,course-v1:GTx+HCIxIII+2T2019,False,discussion,Design Cycle in education,"Speaking with teachers, students, and parents ...",False,False,0,0,0,12/4/19 17:20,12/4/19 17:20,12/4/19 17:20
9272,\x35646537343339666337363237373039363330303232...,16397,d935eb4e7b1a8272cb70c46d13e6848237f9ac5d,course-v1:GTx+HCIxIII+2T2019,False,discussion,Prototyping for internal operational tools,I would start with verbal first to talk with u...,False,False,0,0,0,12/4/19 5:26,12/4/19 5:26,12/4/19 5:26
9273,\x35646266366537656337363237373039336630303038...,16397,e478841103a48711484f884297bca5988eec3ad2,course-v1:GTx+HCIxIII+2T2019,False,discussion,Needfinding for book reading,Figure out our targeted users and brainstorm t...,False,False,0,0,0,11/4/19 0:19,11/4/19 0:19,11/4/19 0:19
9274,\x35646266366161323935623036323039353630303037...,16397,95c784fe2c116a1d78367875887ff3e49aab3d2c,course-v1:GTx+HCIxIII+2T2019,False,discussion,What's wrong with the survey?,* the first question and the third should labe...,False,False,0,0,0,11/4/19 0:02,11/4/19 0:02,11/4/19 0:02
9275,\x35646233386331356337363237373039323030303030...,16397,d84fefc5541960f7b550df2c268c6d380ab12b6a,course-v1:GTx+HCIxIII+2T2019,False,discussion,Data Use Policy and Consent,"Personally, I would want Facebook to get an ex...",True,False,0,0,0,10/25/19 23:58,10/25/19 23:58,10/25/19 23:58
9276,\x35646166633861356330366432363039346630303437...,16397,6e0f814acdaa4cf2d1315f2654331b9ff981b253,course-v1:GTx+HCIxIII+2T2019,False,discussion,Large System Operational Tools,The users I need are the people who handle ope...,False,False,1,0,0,10/23/19 3:35,10/23/19 3:35,10/23/19 3:27
9277,\x35646166396566633834343532613037616330303436...,16397,1c47923a60039e404c8c611bb6e3853a11545e2f,course-v1:GTx+HCIxIII+2T2019,False,discussion,Importance of the Design,Well the reason why I decided to take this cla...,False,False,0,0,0,10/23/19 0:29,10/23/19 0:29,10/23/19 0:29
9278,\x35616665346166663834343532613038343530303565...,17452853,49e7d0f24c50cfe627e46d6b2f8b9cfc828814a3,course-v1:GTx+ISYE6501x+2T2018,False,discussion,"Hello from Grace, Toronto, CA","Hi all, this is Grace! Would love to meet anyo...",False,False,0,0,0,5/18/18 3:39,5/18/18 3:39,5/18/18 3:39
9279,\x35616661666164623234343531613039623230303561...,17450629,49e7d0f24c50cfe627e46d6b2f8b9cfc828814a3,course-v1:GTx+ISYE6501x+2T2018,False,discussion,Hello!,Hello all! My name is PERSON and I'm currently...,False,False,0,0,0,5/15/18 15:20,5/15/18 15:20,5/15/18 15:20
9280,\x35616631303330613834343532613038343230303536...,14334853,course,course-v1:GTx+MGT6203x+2T2018,False,discussion,Intended grading scale?,My final exam grade was rounded down 9.8% to f...,False,False,5,4,0,5/15/18 15:49,5/15/18 15:49,5/8/18 1:53
9281,\x35616630363738633234343531613039646330303532...,15680341,course,course-v1:GTx+MGT6203x+2T2018,False,question,Final Exam Grading Input,"Hi, as per the instructions we received last w...",True,False,1,0,0,5/7/18 16:30,5/7/18 16:30,5/7/18 14:49
9282,\x35613864303938333234343531613039626530303134...,6778107,8088b638e41c2c04751500584ee3d57eb21edc5d,course-v1:GTx+MGT6203x+2T2018,False,question,I am assigned to wrong session,"Dear Sir, Data Analytics for Business GTx - ...",False,False,1,0,0,3/8/18 14:51,3/8/18 14:51,2/21/18 5:54
9283,\x35613838623331663234343531613039656230303131...,17036256,course,course-v1:GTx+MGT6203x+2T2018,False,discussion,Syllabus Dates,Question about the syllabus due dates. It see...,False,False,2,0,0,2/19/18 3:37,2/19/18 3:37,2/17/18 22:56